### ISSUE TITLE
drift in the z axis

### ISSUE THREAD

**Issue by Flandoe** [Pamphlett/CoBigICP#2]
I use this method to test my data, but I find the trajectory drifts in the z-axis. Could you give some advice to solve this problem? Thanks.
![image](https://user-images.githubusercontent.com/10720908/131849937-5405bb72-e119-4c60-ac15-38400b6207cd.png)

**Comment by Pamphlett** [comment]
Hi Flandoe,

Thanks for your interest.
Could you specify the data you use? (LiDAR type and environment)
And if possible provide the data with me so I can have my hands on it.

**Comment by Flandoe** [comment]
> you specify the data you use? (L

Hi, Pamphlett.
Thank you for your quick reply. I am sorry I cannot share the data. The environment is a tunnel and I use the .pcd file format. The following code is how to read the .pcd file.
`RefData_pcd = pcread(path_ref);
RefData = RefData_pcd.Location';`

**Comment by Pamphlett** [comment]
Hi @Flandoe ,

Tunnels-like scenario has always been the toughest as we lacking constraints in the along-tunnel direction.

In that case, I suggest

- try to provide an initial value, either from an IMU or just use the former pose estimation result as the current initial value (under the assumption that scans distribute evenly in the tunnel), to CoBigICP.

Also, what kind of LiDAR are you using?
Denser point clouds allows for more precise statistical info computation, which means you have a better chance to have a better pose estimation result.

**Comment by Flandoe** [comment]
> Hi @Flandoe ,
> 
> Tunnels-like scenario has always been the toughest as we lacking constraints in the along-tunnel direction.
> 
> In that case, I suggest
> 
> * try to provide an initial value, either from an IMU or just use the former pose estimation result as the current initial value (under the assumption that scans distribute evenly in the tunnel), to CoBigICP.
> 
> Also, what kind of LiDAR are you using?
> Denser point clouds allows for more precise statistical info computation, which means you have a better chance to have a better pose estimation result.

I totally agree with what you said about the tunnel-like scenario. Thank you for your suggestion. I will try. 
I use 2*16 line LiDAR, of which one is placed horizontally and the other is placed vertically. This is why I am confused about the drift in the z-axis because the vertical LiDAR can constrain it.

**Comment by Pamphlett** [comment]
No problem.
As I cannot access the data, I couldn't dive deeper into this issue.
Hope you could resolve it!

**Comment by Pamphlett** [comment]
I close this issue since there is no update. Feel free to open it again.
